"""empty message

Revision ID: 4fa4b019146d
Revises: 
Create Date: 2019-12-13 10:47:12.333074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fa4b019146d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cima_enterprise',
    sa.Column('ruc', sa.String(length=30), nullable=False),
    sa.Column('business_name', sa.String(length=500), nullable=True),
    sa.Column('suitable', sa.Float(), nullable=True),
    sa.Column('final_rate', sa.Float(), nullable=True),
    sa.Column('client_dni', sa.String(length=30), nullable=True),
    sa.Column('client_first_name', sa.String(length=255), nullable=True),
    sa.Column('client_last_name', sa.String(length=255), nullable=True),
    sa.Column('sbs_clasification', sa.String(length=10), nullable=True),
    sa.Column('max_pd', sa.Float(), nullable=True),
    sa.Column('company_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ruc'),
    sa.UniqueConstraint('ruc')
    )
    op.create_table('cima_loan_calendar',
    sa.Column('quota_order', sa.Integer(), nullable=False),
    sa.Column('credit_code', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('disburse_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('quota_duration_days', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('pending_capital', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('amortization', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('effective_payment_date', sa.Date(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('disbursed_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('quota_order', 'credit_code', 'document_type', 'document_number')
    )
    op.create_table('cima_loan_debt',
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('credit_code', sa.String(length=50), nullable=False),
    sa.Column('quota_order', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('days_expired', sa.Integer(), nullable=True),
    sa.Column('expired_debt_interest', sa.Float(), nullable=True),
    sa.Column('compensatory_interest', sa.Float(), nullable=True),
    sa.Column('collection_penalty', sa.Float(), nullable=True),
    sa.Column('total_partial_paid', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('document_type', 'document_number', 'credit_code', 'quota_order')
    )
    op.drop_table('ibk_loan_calendar')
    op.drop_table('ibk_data')
    op.drop_table('ibk_loan_debt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibk_loan_debt',
    sa.Column('document_type', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('document_number', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('credit_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('quota_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('days_expired', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('expired_debt_interest', mysql.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('compensatory_interests', mysql.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('collection_penalty', mysql.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('total_partial_paid', mysql.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('total_debt', mysql.DECIMAL(precision=16, scale=2), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ibk_data',
    sa.Column('RUC', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('BUSINESS_NAME', mysql.VARCHAR(length=600), nullable=True),
    sa.Column('SUITABLE', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('FINAL_RATE', mysql.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('CLIENT_DNI', mysql.VARCHAR(length=600), nullable=True),
    sa.Column('CLIENT_FIRST_NAME', mysql.VARCHAR(length=600), nullable=True),
    sa.Column('CLIENT_LAST_NAME', mysql.TEXT(), nullable=True),
    sa.Column('SBS_CLASSIFICATION', mysql.VARCHAR(charset='utf8mb4', length=1), nullable=True),
    sa.Column('MAX_PD', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('COMPANY_TYPE', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ibk_loan_calendar',
    sa.Column('quota_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('credit_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('document_type', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('document_number', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('disburse_date', sa.DATE(), nullable=True),
    sa.Column('payment_date', sa.DATE(), nullable=True),
    sa.Column('quota_duration_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('pending_capital', mysql.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('interest', mysql.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('amortization', mysql.DECIMAL(precision=16, scale=2), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('effective_payment_date', sa.DATE(), nullable=True),
    sa.Column('interest_rate', mysql.DECIMAL(precision=16, scale=4), nullable=True),
    sa.Column('disbursed_amount', mysql.DECIMAL(precision=16, scale=4), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('cima_loan_debt')
    op.drop_table('cima_loan_calendar')
    op.drop_table('cima_enterprise')
    # ### end Alembic commands ###
