"""empty message

Revision ID: e4608849c3f3
Revises: 635413e36115
Create Date: 2019-12-12 21:33:18.742458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4608849c3f3'
down_revision = '635413e36115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intents',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NUM_DOC', sa.String(length=30), nullable=True),
    sa.Column('CONTEXT', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('NUM_DOC')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NAME', sa.String(length=100), nullable=True),
    sa.Column('PRIZE', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('NAME')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('intents')
    # ### end Alembic commands ###
